name: "Lint PR Title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (default is angular commit conventions).
          # You can add custom types here if needed.
          types: |
            fix
            feat
            docs
            ci
            chore
            style
            refactor
            perf
            test
          # Configure that a scope is optional but allowed.
          requireScope: false
